# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dad148bcb93851e896e49c9443a5f5791f0bdab55ac424fe3f11a6ff76723fe9571a4e90a8dc988fbfb15989b27f12bc2cf25bc7293a10df9e5c24e4d1b1f51e

test:
  secret_key_base: cd77554390c7182393f6a4cd67bbcdae66d885bb9b8934ca68a17b15c40e037e9323af42615778c64c20b1452bbb13f9d9dc18055231f44cbaf106bf43d93024

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
